backend:
  name: github
  repo: bundoon/bundoon-astro     # your actual repo
  branch: main
  base_url: https://petersblog.bundoon.org
  auth_endpoint: /api/auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
